# Generated by Django 5.0 on 2024-02-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_photo_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='book/cover/%Y/%m'),
        ),
    ]
