# Generated by Django 5.0 on 2024-02-16 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_comment_author_book_alter_comment_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
